name: Fetch API

on:
  workflow_dispatch:
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: move
        run: node move.js
      - name: verify
        run: node see.js
